spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 936nbm51QemjwLw74C
    url: jdbc:postgresql://localhost:5432/security
    username: user
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: hikari-jdbc-pool-security
      auto-commit: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    jdbc:
      dialect: postgresql

  rabbitmq:
    host: localhost
    port: 5672
    username: RabbitMQ
    password: RabbitMQ

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka