spring:
  config:
    activate:
      on-profile: dev
  application:
    name: crm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 936nbm51QemjwLw74C
    url: jdbc:mysql://localhost:3306/crm?useTimezone=true&serverTimezone=UTC
    username: crm_user
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: hikari-jdbc-pool-crm
      auto-commit: true
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  data:
    jdbc:
      dialect: mysql

  rabbitmq:
    host: localhost
    port: 5672
    username: wesley
    password: "S#phi@2601"
